version: "3"

services:
  taker:
    restart: on-failure
    build:
      context: ./
      dockerfile: ./docker/taker/Dockerfile
    extra_hosts:
      - "dockerhost:192.168.114.145"
    logging:
      driver: "json-file"
      options:
        max-size: "300m"
        max-file: "10"
  receiver:
    restart: on-failure
    build:
      context: ./
      dockerfile: ./docker/receiver/Dockerfile
    ports:
      - 4000:4000
    extra_hosts:
      - "dockerhost:192.168.114.145"
    logging:
      driver: "json-file"
      options:
        max-size: "300m"
        max-file: "10"