version: "3"

services:
  taker:
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8090:8090
      - 8091:8091
    environment:
      - PORT=8090
      - DIAG_PORT=8091
    extra_hosts:
      - "dockerhost:192.168.114.145"
    logging:
      driver: "json-file"
      options:
        max-size: "300m"
        max-file: "10"